# This workflow will install Python dependencies, lint and run tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:

permissions:
  contents: read

jobs:
  functional_testing:
    runs-on: ubuntu-latest
    # Skip if got triggered by a PR that is still in draft
    if: github.event.pull_request.draft == false  
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r setup/requirements.txt
      - name: Bazel build
        run: |
          bazel build //...
      - name: Test with bazel and pytest
        run: |
          bazel test //... --test_output=all
